language: go

go:
      - 1.x
      - 1.6
      - 1.7.x
      - master
install:
      - go get github.com/howeyc/fsnotify 
      - go get github.com/mattn/go-sqlite3  
      - go get github.com/robfig/config   
